# Site settings
title: HoneyMoon à San Francisco
email: christophe@robiweb.net
description: > # this means to ignore newlines until "baseurl:"
  Paris - San Francisco - Yosemite National Park :
  Le bonheur à l'état brut d'Alexandra et Christophe. Tout simplement.
baseurl: "/honeymoon" # the subpath of your site, e.g. /blog/
url: "http://tempslibre.robillard.pro" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
timezone: Europe/Paris

# Build settings
markdown: kramdown
